### ISSUE TITLE
Anchor Map

### ISSUE THREAD

**Issue by andrewtran1995** [Kaikat/ATlatoque#5]
* Move corners of anchor until it works
* Figure out good approach (look up help online)

**Comment by andrewtran1995** [comment]
@Kaikat, just for clarification, the map should still be able to pan, correct? By fixing the anchors of the map, we are trying to fix the Unity anchor objects of the Map image so that it scales correctly to different phone resolutions.

**Comment by Kaikat** [comment]
At the current zoom level it should be able to pan up and down.

If it were to zoom more it should be able to pan both up and down and right and left such that all areas on the current map are always visible since it has the area of interest.

It could also be that if the person pans after a certain point the map resets to the area of interest since nothing is out of the map piece currently shown.
